spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/images}
    username: ${DB_USER:developer}
    password: ${DB_PASS:password}
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5000000
server:
  forward-headers-strategy: framework
  port: 8001

